name = "gnatprove"
version = "12.1.1"
description = "Automatic formal verification of SPARK code"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "GPL-3.0-or-later"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[origin."case(os)".windows."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-12.1.0-1/gnatprove-x86_64-windows64-12.1.0-1.tar.gz"
hashes = ["sha256:e46f520d6566cc21a707facb05c1e5c8fb9d50c6b981f9026277e9ab5ad93bcc"]

[origin."case(os)".macos."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-12.1.0-1/gnatprove-x86_64-darwin-12.1.0-1.tar.gz"
hashes = ["sha256:a8206aba6a6df42ceff0786a0204972da2ac795807671f3409728fdb90191825"]

[origin."case(os)".linux."case(word-size)".bits-64]
url = "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gnatprove-12.1.0-1/gnatprove-x86_64-linux-12.1.0-1.tar.gz"
hashes = ["sha256:59a10e38b1dc52161bd6263717a1566ef3387c12a97624a99664f78b8f30e6ac"]
